# Backend configuration
backend:
  name: pophin-back # TODO - Nommer votre application backend
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0 # TODO - Mettre l'image à déployer
  containerPort: 8080 # TODO - Précisez le port d'écoute du conteneur
  host: valentin-gilles-backend.codelab.cloud-sp.eu # TODO - Précisez l'hôte d'exposition du backend
  service:
    port: 443 # TODO - Précisez le port d'exposition du service de votre pod